// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class HotelCommentView
{
    public string FCommentContent { get; set; }

    public decimal? FCommentScore { get; set; }

    public DateTime? FCommentTime { get; set; }

    public string CustomerName { get; set; }

    public string CustomerImagePath { get; set; }

    public int? DayCount { get; set; }

    public int? FGuestCount { get; set; }

    public string FRoomTypeName { get; set; }

    public int FHotelId { get; set; }
}