// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using prjTravelPlatformV3.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace prjTravelPlatformV3.Models
{
    public partial interface IdbTravalPlatformContextProcedures
    {
        Task<List<GetAvailableRoomsResult>> GetAvailableRoomsAsync(DateTime? checkInDate, DateTime? checkOutDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAvailableRoomsByHotelIdResult>> GetAvailableRoomsByHotelIdAsync(int? hotelId, DateTime? checkInDate, DateTime? checkOutDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAvailableRoomsByHotelIdTestResult>> GetAvailableRoomsByHotelIdTestAsync(int? hotelId, DateTime? checkInDate, DateTime? checkOutDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAvailableRoomsEditResult>> GetAvailableRoomsEditAsync(int? HotelId, int? RoomTypeId, DateTime? CheckInDate, DateTime? CheckOutDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAvailableRoomsEditFilterByHotelIdResult>> GetAvailableRoomsEditFilterByHotelIdAsync(int? HotelId, DateTime? CheckInDate, DateTime? CheckOutDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
