// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarRentOrderDetailView
{
    public int FOrderDetailId { get; set; }

    public string FOrderId { get; set; }

    public string FLicensePlateNum { get; set; }

    public string FModelName { get; set; }

    public string FName { get; set; }

    public string FId { get; set; }

    public int? FAge { get; set; }

    public string FPhone { get; set; }

    public DateTime? FFromDateTime { get; set; }

    public string FServicePoint { get; set; }

    public DateTime? FRentDateTime { get; set; }

    public string FRentServicePoint { get; set; }

    public decimal? FPrice { get; set; }
}