// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarInfoView
{
    public int FCarId { get; set; }

    public string FLicensePlateNum { get; set; }

    public string FModelName { get; set; }

    public int? FNumOfPsgr { get; set; }

    public int? FNumOfLuggage { get; set; }

    public string FDescription { get; set; }

    public string FDescription2 { get; set; }

    public decimal? FRentalFee { get; set; }

    public string FImagePath { get; set; }

    public string FServicePoint { get; set; }

    public string FCompanyName { get; set; }

    public bool? FRentStatus { get; set; }
}