// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarModelInfoView
{
    public int FModelId { get; set; }

    public string FModelName { get; set; }

    public int? FNumOfPsgr { get; set; }

    public int? FNumOfLuggage { get; set; }

    public string FDescription { get; set; }

    public string FDescription2 { get; set; }

    public decimal? FRentalFee { get; set; }

    public string FImagePath { get; set; }

    public bool? FModelInUse { get; set; }
}