// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarRentOrderInfoView
{
    public string FOrderId { get; set; }

    public int? FMemberId { get; set; }

    public string FName { get; set; }

    public string FEmail { get; set; }

    public string FPhone { get; set; }

    public string FCouponName { get; set; }

    public string FPayment { get; set; }

    public string FPaymentStatus { get; set; }

    public string FOrderStatus { get; set; }

    public string FOrderDate { get; set; }

    public decimal? FTotalPrice { get; set; }
}