// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TDcCouponList
{
    public int FCouponId { get; set; }

    public string FCouponCode { get; set; }

    public string FCouponName { get; set; }

    public string FDiscountType { get; set; }

    public decimal? FDiscount { get; set; }

    public decimal? FAmount { get; set; }

    public DateTime? FStartDate { get; set; }

    public DateTime? FEndDate { get; set; }

    public string FRule { get; set; }

    public string FProductType { get; set; }

    public string FNote { get; set; }

    public bool? FEnable { get; set; }

    public string FimagePath { get; set; }

    public virtual ICollection<TDcCusCouponQty> TDcCusCouponQties { get; set; } = new List<TDcCusCouponQty>();

    public virtual ICollection<TForder> TForders { get; set; } = new List<TForder>();

    public virtual ICollection<THorder> THorders { get; set; } = new List<THorder>();

    public virtual ICollection<TIorder> TIorders { get; set; } = new List<TIorder>();

    public virtual ICollection<TRcarRentOrder> TRcarRentOrders { get; set; } = new List<TRcarRentOrder>();

    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();

    public virtual ICollection<TdestinationOrder> TdestinationOrders { get; set; } = new List<TdestinationOrder>();

    public virtual ICollection<TfreeOrder> TfreeOrders { get; set; } = new List<TfreeOrder>();

    public virtual ICollection<TtravelOrder> TtravelOrders { get; set; } = new List<TtravelOrder>();
}