// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TDcProductType
{
    public int FId { get; set; }

    public string FTypeName { get; set; }

    public string FTypeLetter { get; set; }
}