// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TdestionationFollow
{
    public string FdestionationId { get; set; }

    public int? FcustomerId { get; set; }

    public int Fid { get; set; }

    public bool Ffollow { get; set; }

    public virtual TCustomer Fcustomer { get; set; }

    public virtual Tdestination Fdestionation { get; set; }
}