// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TfreePlanDetail
{
    public int FdestinationDetailId { get; set; }

    public int? FcustomerId { get; set; }

    public string FdestinationId { get; set; }

    public int? FtravelDay { get; set; }

    public TimeSpan? FdestionationTime { get; set; }

    public string FfreeId { get; set; }

    public bool? FdestionationState { get; set; }

    public virtual TCustomer Fcustomer { get; set; }

    public virtual Tdestination Fdestination { get; set; }

    public virtual TfreePlan Ffree { get; set; }
}