// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TfreePlan
{
    public string FfreeId { get; set; }

    public bool? Fstate { get; set; }

    public int? FmemberId { get; set; }

    public virtual ICollection<TfreeOrder> TfreeOrders { get; set; } = new List<TfreeOrder>();

    public virtual ICollection<TfreePlanDetail> TfreePlanDetails { get; set; } = new List<TfreePlanDetail>();
}