// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TfreeOrder
{
    public string ForderId { get; set; }

    public int? FmemberId { get; set; }

    public int? Fqty { get; set; }

    public string FfreeId { get; set; }

    public DateTime? ForderDate { get; set; }

    public int? FcoupomId { get; set; }

    public decimal? Fprice { get; set; }

    public bool? ForderSate { get; set; }

    public virtual TDcCouponList Fcoupom { get; set; }

    public virtual TfreePlan Ffree { get; set; }

    public virtual TCustomer Fmember { get; set; }
}