// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIorderDetailView
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public string FProductName { get; set; }

    public string FSpecName { get; set; }

    public int? FQty { get; set; }

    public decimal? FPrice { get; set; }

    public decimal? FSubtotal { get; set; }
}