// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIorderView
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public string FCompanyName { get; set; }

    public int FCustomerId { get; set; }

    public string FName { get; set; }

    public string FOrderDate { get; set; }

    public string FPayment { get; set; }

    public string FCouponName { get; set; }

    public string FNotes { get; set; }

    public string FLogisticsName { get; set; }

    public decimal? FTotal { get; set; }

    public string FShipName { get; set; }

    public string FShipPhone { get; set; }

    public string FShipAddress { get; set; }

    public string FStatus { get; set; }
}