// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIproductReviewsView
{
    public int FId { get; set; }

    public string Profilepic { get; set; }

    public string FName { get; set; }

    public string FReviewDate { get; set; }

    public string FProductName { get; set; }

    public string FSpecName { get; set; }

    public double? FProductScore { get; set; }

    public string FProductReview { get; set; }

    public string FImagePath { get; set; }
}