// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIproductListView
{
    public int FProductId { get; set; }

    public string FCompanyName { get; set; }

    public string FImagePath { get; set; }

    public string FProductName { get; set; }

    public string FType { get; set; }

    public string FDescription { get; set; }

    public decimal? FPrice { get; set; }

    public int TotalQty { get; set; }

    public double AvgScore { get; set; }
}