// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIproductReview
{
    public int FId { get; set; }

    public int? FCustomerId { get; set; }

    public int? FProductSpecId { get; set; }

    public string FReviewDate { get; set; }

    public double? FProductScore { get; set; }

    public string FProductReview { get; set; }

    public string FImagePath { get; set; }

    public virtual TIproductSpec FProductSpec { get; set; }
}