// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TMessageInfo
{
    public int FId { get; set; }

    public string SelfId { get; set; }

    public string SendToId { get; set; }

    public string Message { get; set; }

    public string SelfMemberId { get; set; }

    public string SendToMemberId { get; set; }

    public string TimeStamp { get; set; }
}