// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class Tpriority
{
    public int Fid { get; set; }

    public string FpriorityName { get; set; }

    public virtual ICollection<Tdestination> Tdestinations { get; set; } = new List<Tdestination>();
}