// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TRcarModelInfo
{
    public string FCode { get; set; }

    public string FDescription { get; set; }

    public string FOpt { get; set; }

    public virtual ICollection<TRcarModel> TRcarModelFCarTypeNavigations { get; set; } = new List<TRcarModel>();

    public virtual ICollection<TRcarModel> TRcarModelFPowerTypeNavigations { get; set; } = new List<TRcarModel>();
}