// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TtravelOrder
{
    public string ForderId { get; set; }

    public int? FmemberId { get; set; }

    public string FplanId { get; set; }

    public int? Fqty { get; set; }

    public DateTime? ForderDate { get; set; }

    public string FpayMethod { get; set; }

    public int Fcoupomid { get; set; }

    public decimal? Fprice { get; set; }

    public bool? ForderState { get; set; }

    public virtual TDcCouponList Fcoupom { get; set; }

    public virtual TCustomer Fmember { get; set; }

    public virtual TtravelPlan Fplan { get; set; }

    public virtual ICollection<TplanRemark> TplanRemarks { get; set; } = new List<TplanRemark>();
}